services:
    ezpublish_legacy.signalslot.base:
        class: eZ\Publish\Core\MVC\Legacy\SignalSlot\AbstractLegacySlot
        public: false
        arguments:
            - "@ezpublish_legacy.kernel"
            - "@ezpublish_legacy.persistence_cache_purger"
            - "@ezpublish_legacy.switchable_http_cache_purger"

    ezpublish_legacy.signalslot.assign_section:
        class: eZ\Publish\Core\MVC\Legacy\SignalSlot\LegacyAssignSectionSlot
        parent: ezpublish_legacy.signalslot.base
        public: false
        tags:
            - { name: ezpublish.api.slot, signal: SectionService\AssignSectionSignal }

    ezpublish_legacy.signalslot.copy_content:
        class: eZ\Publish\Core\MVC\Legacy\SignalSlot\LegacyCopyContentSlot
        parent: ezpublish_legacy.signalslot.base
        public: false
        tags:
            - { name: ezpublish.api.slot, signal: ContentService\CopyContentSignal }

    ezpublish_legacy.signalslot.create_location:
        class: eZ\Publish\Core\MVC\Legacy\SignalSlot\LegacyCreateLocationSlot
        parent: ezpublish_legacy.signalslot.base
        public: false
        tags:
            - { name: ezpublish.api.slot, signal: LocationService\CreateLocationSignal }

    ezpublish_legacy.signalslot.delete_content:
        class: eZ\Publish\Core\MVC\Legacy\SignalSlot\LegacyDeleteContentSlot
        parent: ezpublish_legacy.signalslot.base
        public: false
        tags:
            - { name: ezpublish.api.slot, signal: ContentService\DeleteContentSignal }

    ezpublish_legacy.signalslot.delete_location:
        class: eZ\Publish\Core\MVC\Legacy\SignalSlot\LegacyDeleteLocationSlot
        parent: ezpublish_legacy.signalslot.base
        public: false
        tags:
            - { name: ezpublish.api.slot, signal: LocationService\DeleteLocationSignal }

    ezpublish_legacy.signalslot.delete_version:
        class: eZ\Publish\Core\MVC\Legacy\SignalSlot\LegacyDeleteVersionSlot
        parent: ezpublish_legacy.signalslot.base
        public: false
        tags:
            - { name: ezpublish.api.slot, signal: ContentService\DeleteVersionSignal }

    ezpublish_legacy.signalslot.hide_location:
        class: eZ\Publish\Core\MVC\Legacy\SignalSlot\LegacyHideLocationSlot
        parent: ezpublish_legacy.signalslot.base
        public: false
        tags:
            - { name: ezpublish.api.slot, signal: LocationService\HideLocationSignal }

    ezpublish_legacy.signalslot.move_subtree:
        class: eZ\Publish\Core\MVC\Legacy\SignalSlot\LegacyMoveSubtreeSlot
        parent: ezpublish_legacy.signalslot.base
        public: false
        tags:
            - { name: ezpublish.api.slot, signal: LocationService\MoveSubtreeSignal }

    ezpublish_legacy.signalslot.publish_version:
        class: eZ\Publish\Core\MVC\Legacy\SignalSlot\LegacyPublishVersionSlot
        parent: ezpublish_legacy.signalslot.base
        public: false
        tags:
            - { name: ezpublish.api.slot, signal: ContentService\PublishVersionSignal }

    ezpublish_legacy.signalslot.set_content_state:
        class: eZ\Publish\Core\MVC\Legacy\SignalSlot\LegacySetContentStateSlot
        parent: ezpublish_legacy.signalslot.base
        public: false
        tags:
            - { name: ezpublish.api.slot, signal: ObjectStateService\SetContentStateSignal }

    ezpublish_legacy.signalslot.create_object_state:
        class: eZ\Publish\Core\MVC\Legacy\SignalSlot\LegacyCreateObjectStateSlot
        parent: ezpublish_legacy.signalslot.base
        public: false
        tags:
            - { name: ezpublish.api.slot, signal: ObjectStateService\CreateObjectStateSignal }

    ezpublish_legacy.signalslot.create_object_state_group:
        class: eZ\Publish\Core\MVC\Legacy\SignalSlot\LegacyCreateObjectStateGroupSlot
        parent: ezpublish_legacy.signalslot.base
        public: false
        tags:
            - { name: ezpublish.api.slot, signal: ObjectStateService\CreateObjectStateGroupSignal }

    ezpublish_legacy.signalslot.delete_object_state:
        class: eZ\Publish\Core\MVC\Legacy\SignalSlot\LegacyDeleteObjectStateSlot
        parent: ezpublish_legacy.signalslot.base
        public: false
        tags:
            - { name: ezpublish.api.slot, signal: ObjectStateService\DeleteObjectStateSignal }

    ezpublish_legacy.signalslot.delete_object_state_group:
        class: eZ\Publish\Core\MVC\Legacy\SignalSlot\LegacyDeleteObjectStateGroupSlot
        parent: ezpublish_legacy.signalslot.base
        public: false
        tags:
            - { name: ezpublish.api.slot, signal: ObjectStateService\DeleteObjectStateGroupSignal }

    ezpublish_legacy.signalslot.set_priority_of_object_state:
        class: eZ\Publish\Core\MVC\Legacy\SignalSlot\LegacySetPriorityOfObjectStateSlot
        parent: ezpublish_legacy.signalslot.base
        public: false
        tags:
            - { name: ezpublish.api.slot, signal: ObjectStateService\SetPriorityOfObjectStateSignal }

    ezpublish_legacy.signalslot.update_object_state:
        class: eZ\Publish\Core\MVC\Legacy\SignalSlot\LegacyUpdateObjectStateSlot
        parent: ezpublish_legacy.signalslot.base
        public: false
        tags:
            - { name: ezpublish.api.slot, signal: ObjectStateService\UpdateObjectStateSignal }

    ezpublish_legacy.signalslot.update_object_state_group:
        class: eZ\Publish\Core\MVC\Legacy\SignalSlot\LegacyUpdateObjectStateGroupSlot
        parent: ezpublish_legacy.signalslot.base
        public: false
        tags:
            - { name: ezpublish.api.slot, signal: ObjectStateService\UpdateObjectStateGroupSignal }

    ezpublish_legacy.signalslot.swap_location:
        class: eZ\Publish\Core\MVC\Legacy\SignalSlot\LegacySwapLocationSlot
        parent: ezpublish_legacy.signalslot.base
        public: false
        tags:
            - { name: ezpublish.api.slot, signal: LocationService\SwapLocationSignal }

    ezpublish_legacy.signalslot.unhide_location:
        class: eZ\Publish\Core\MVC\Legacy\SignalSlot\LegacyUnhideLocationSlot
        parent: ezpublish_legacy.signalslot.base
        public: false
        tags:
            - { name: ezpublish.api.slot, signal: LocationService\UnhideLocationSignal }

    ezpublish_legacy.signalslot.update_location:
        class: eZ\Publish\Core\MVC\Legacy\SignalSlot\LegacyUpdateLocationSlot
        parent: ezpublish_legacy.signalslot.base
        public: false
        tags:
            - { name: ezpublish.api.slot, signal: LocationService\UpdateLocationSignal }

    ezpublish_legacy.signalslot.publish_content_type_draft:
        class: eZ\Publish\Core\MVC\Legacy\SignalSlot\LegacyPublishContentTypeDraftSlot
        parent: ezpublish_legacy.signalslot.base
        public: false
        tags:
            - { name: ezpublish.api.slot, signal: ContentTypeService\PublishContentTypeDraftSignal }

    ezpublish_legacy.signalslot.create_language:
        class: eZ\Publish\Core\MVC\Legacy\SignalSlot\LegacyCreateLanguageSlot
        parent: ezpublish_legacy.signalslot.base
        public: false
        tags:
            - { name: ezpublish.api.slot, signal: LanguageService\CreateLanguageSignal }

    ezpublish_legacy.signalslot.delete_language:
        class: eZ\Publish\Core\MVC\Legacy\SignalSlot\LegacyDeleteLanguageSlot
        parent: ezpublish_legacy.signalslot.base
        public: false
        tags:
            - { name: ezpublish.api.slot, signal: LanguageService\DeleteLanguageSignal }

    ezpublish_legacy.signalslot.disable_language:
        class: eZ\Publish\Core\MVC\Legacy\SignalSlot\LegacyDisableLanguageSlot
        parent: ezpublish_legacy.signalslot.base
        public: false
        tags:
            - { name: ezpublish.api.slot, signal: LanguageService\DisableLanguageSignal }

    ezpublish_legacy.signalslot.enable_language:
        class: eZ\Publish\Core\MVC\Legacy\SignalSlot\LegacyEnableLanguageSlot
        parent: ezpublish_legacy.signalslot.base
        public: false
        tags:
            - { name: ezpublish.api.slot, signal: LanguageService\EnableLanguageSignal }

    ezpublish_legacy.signalslot.update_language_name:
        class: eZ\Publish\Core\MVC\Legacy\SignalSlot\LegacyUpdateLanguageNameSlot
        parent: ezpublish_legacy.signalslot.base
        public: false
        tags:
            - { name: ezpublish.api.slot, signal: LanguageService\UpdateLanguageNameSignal }

    ezpublish_legacy.signalslot.update_user:
        class: eZ\Publish\Core\MVC\Legacy\SignalSlot\LegacyUpdateUserSlot
        parent: ezpublish_legacy.signalslot.base
        public: false
        tags:
            - { name: ezpublish.api.slot, signal: UserService\UpdateUserSignal }

    ezpublish_legacy.signalslot.create_user:
        class: eZ\Publish\Core\MVC\Legacy\SignalSlot\LegacyCreateUserSlot
        parent: ezpublish_legacy.signalslot.base
        public: false
        tags:
            - { name: ezpublish.api.slot, signal: UserService\CreateUserSignal }

    ezpublish_legacy.signalslot.assign_user_to_user_group:
        class: eZ\Publish\Core\MVC\Legacy\SignalSlot\LegacyAssignUserToUserGroupSlot
        parent: ezpublish_legacy.signalslot.base
        public: false
        tags:
            - { name: ezpublish.api.slot, signal: UserService\AssignUserToUserGroupSignal }

    ezpublish_legacy.signalslot.unassign_user_from_user_group:
        class: eZ\Publish\Core\MVC\Legacy\SignalSlot\LegacyUnassignUserFromUserGroupSlot
        parent: ezpublish_legacy.signalslot.base
        public: false
        tags:
            - { name: ezpublish.api.slot, signal: UserService\UnAssignUserFromUserGroupSignal }
